// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tevkmkadkgwgdutbjztu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRldmtta2Fka2d3Z2R1dGJqenR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzMTcwNjksImV4cCI6MjA4Mzg5MzA2OX0.onM65aqnm2_It4VwW3U9PxsLndz2CbddbDfrjfTo4_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});